### ISSUE TITLE
Syntax highlighting breaks on apostrophe in comment

### ISSUE THREAD

**Issue by alimbada** [MarkusAmshove/vscode-natural#45]
Syntax highlighting breaks when there is an apostrophe in a comment which starts with multiple asterisks

Sample code:

```
DEFINE SUBROUTINE FOO
** The bird's the word
END-SUBROUTINE
END
```

This breaks the highlighting for the rest of the file.

**Comment by MarkusAmshove** [comment]
Thank you for bringing this up, will be fixed in #46  :-)
